# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink: /:categories/:year/:month/:day/:title 

exclude: [".ruby-version", ".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: "pygments"

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
paginate:         10
baseurl:          http://joshualane.com/
url:              http://joshualane.com/

title : "Josh Lane"
tagline: "Code that I felt like sharing"
author :
  name : Joshua Lane
  email : me@joshualane.com
  github : lanej
  twitter : lanejoshlane

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lanej/lanej.github.com
